Feature/return label bundles
fond-of-oryx/fond-of-oryx pull request #105
Opened 2021-05-03 06:51 UTC by DerCalli

**epic, merged branches:** 

- return-labels-rest-api: glue layer + unit tests (#99)
- return-labels-rest-api: client layer + unit tests (#100)
- return-labels-rest-api: zed layer + unit tests (#104)

2021-05-05 09:02 UTC, daniel-rose commented
@DerCalli please use POST for resource "return-labels". https://restfulapi.net/http-methods/

2021-05-05 09:04 UTC, daniel-rose requested changes
@DerCalli please use POST for resource "return-labels". https://restfulapi.net/http-methods/

2021-05-05 09:17 UTC, DerCalli commented
> @DerCalli please use POST for resource "return-labels". https://restfulapi.net/http-methods/

@daniel-rose: i already talked about that with chris yesterday. it was a wish from frontend to use GET instead POST. i was a little bit confused about that. i will turn in back

2021-05-17 07:50 UTC, sourcecube approved these changes

2021-05-17 12:24 UTC, daniel-rose approved these changes

2021-05-17 12:31 UTC, merged