Feature/add rest endpoint
fond-of-oryx/fond-of-oryx pull request #13
Opened 2021-03-02 10:34 UTC by SpiderDan98

Add one-time-password-rest-api

2021-03-03 07:11 UTC, sourcecube commented on bundles/one-time-password-rest-api/LICENSE
> +Copyright (c) 2020 FOND OF GmbH
2021 (;

2021-03-03 07:11 UTC, sourcecube commented on bundles/one-time-password-rest-api/composer.json
> +    "fond-of-codeception/spryker": "dev-master as 1.0.0",
You can use 1.0.0, it was released 8 days ago (:

2021-03-03 07:11 UTC, sourcecube commented on bundles/one-time-password-rest-api/src/FondOfOryx/Shared/OneTimePasswordRestApi/Transfer/one_time_password_rest_api.transfer.xml
> +    <transfer name="OneTimePasswordResponse">
Should this be namespaced with `Rest` as well like the request? Or ist that how it's done in Spyker core?

2021-03-03 07:11 UTC, sourcecube commented on bundles/one-time-password/LICENSE
> +Copyright (c) 2020 FOND OF GmbH
2021.. and for future record, these files should be in a separate PR

2021-03-03 07:11 UTC, sourcecube commented on bundles/one-time-password/composer.json
> +    "fond-of-codeception/spryker": "dev-master as 1.0.0",
`^1.0`

2021-03-03 07:11 UTC, sourcecube commented on bundles/one-time-password-rest-api/src/FondOfOryx/Glue/OneTimePasswordRestApi/OneTimePasswordRestApiConfig.php
> +    public const EMAIL_REQUIRED_ERROR_DETAIL = 'The attribute Email is required.';
Nice! Maybe add a comment like .. "The code is not related to a system yet, might change later"

2021-03-03 07:12 UTC, sourcecube commented on bundles/one-time-password-rest-api/src/FondOfOryx/Glue/OneTimePasswordRestApi/Processor/OneTimePasswordProcessor.php
> +    }
You could add a test for this to make sure that the error will be returned

2021-03-03 07:12 UTC, sourcecube approved these changes

2021-03-03 07:13 UTC, sourcecube commented
Good work 🎉

2021-03-03 09:56 UTC, daniel-rose requested changes

2021-03-03 09:56 UTC, daniel-rose commented on bundles/one-time-password-rest-api/composer.json
> +    "spryker/glue-application": "^1.21.0"
Please use ^1.0.0

2021-03-03 09:56 UTC, daniel-rose commented on bundles/one-time-password-rest-api/composer.json
> +    "php": ">=7.2",
7.2 EOL

2021-03-03 09:56 UTC, daniel-rose commented on composer.json
> +    "spryker/glue-application": "^1.21.0",
Use ^1.0.0

2021-03-16 10:49 UTC, daniel-rose approved these changes
Keep it mind at dandelion.json

2021-03-16 10:49 UTC, daniel-rose commented on bundles/one-time-password-rest-api/composer.json
> +    "fond-of-codeception/spryker": "^1.0.0",
use only `"fond-of-codeception/spryker": "^1.0",`

2021-03-16 10:49 UTC, daniel-rose commented on bundles/one-time-password-rest-api/composer.json
> +    "phpro/grumphp": "^0.14",
remove unused stuff

2021-03-16 10:49 UTC, daniel-rose commented on bundles/one-time-password-rest-api/composer.json
> +    "spryker/development": "^3.6"
Why?

2021-03-16 10:49 UTC, daniel-rose commented on bundles/one-time-password-rest-api/composer.json
> +    "sebastian/phpcpd": "^4.0",
Why?

2021-03-16 10:49 UTC, daniel-rose commented on bundles/one-time-password-rest-api/composer.json
> +      "Generated\\": "tests/Generated/"
`"Generated\\": "src/Generated/"`

2021-03-16 10:49 UTC, daniel-rose commented on bundles/one-time-password-rest-api/src/FondOfOryx/Client/OneTimePasswordRestApi/OneTimePasswordRestApiDependencyProvider.php
> +            function (Container $container) {
use static closure please.. (performance)

2021-03-16 10:49 UTC, daniel-rose commented on bundles/one-time-password-rest-api/src/FondOfOryx/Client/OneTimePasswordRestApi/OneTimePasswordRestApiFactory.php
> +    public function getZedRequestClient(): OneTimePasswordRestApiToZedRequestClientInterface
Can be protected...

2021-03-16 10:49 UTC, daniel-rose commented on bundles/one-time-password-rest-api/src/FondOfOryx/Client/OneTimePasswordRestApi/Zed/OneTimePasswordRestApiStub.php
> +*/
CodeStyle...

2021-03-16 10:49 UTC, daniel-rose commented on bundles/one-time-password-rest-api/src/FondOfOryx/Glue/OneTimePasswordRestApi/Controller/OneTimePasswordResourceController.php
> +     * @param \Spryker\Glue\GlueApplication\Rest\Request\Data\RestRequestInterface $restRequest
Add glue annotation please (for auto doc) --> https://documentation.spryker.com/docs/documenting-glue-api-resources#rest-methods

2021-03-16 10:49 UTC, daniel-rose commented on bundles/one-time-password-rest-api/src/FondOfOryx/Glue/OneTimePasswordRestApi/Processor/OneTimePasswordProcessor.php
> +            ->setStatus(204);
Use const for this. (HttpFoundation from Symfony)

2021-03-16 10:49 UTC, daniel-rose commented on bundles/one-time-password-rest-api/src/FondOfOryx/Glue/OneTimePasswordRestApi/Processor/OneTimePasswordProcessor.php
> +        $restErrorMessageTransfer->setStatus(400)
Same

2021-03-16 10:49 UTC, daniel-rose commented on bundles/one-time-password-rest-api/tests/FondOfOryx/Glue/OneTimePasswordRestApi/Processor/OneTimePasswordProcessorTest.php
> +            ->with(204)
Const from HttpFoundation

2021-03-16 10:49 UTC, daniel-rose commented on bundles/one-time-password/composer.json
> +    "php": ">=7.2"
EOL for 7.2. Please use >= 7.3...

2021-03-16 10:49 UTC, daniel-rose commented on bundles/one-time-password/composer.json
> +      "Generated\\": "tests/Generated/"
Look at composer.json from one-time-password-rest-api...

2021-03-16 20:34 UTC, julianzimmermann approved these changes

2021-03-16 20:34 UTC, julianzimmermann commented on bundles/one-time-password-rest-api/composer.json
> +      "Generated\\": "tests/Generated/"
src/Generated/

2021-03-17 12:00 UTC, merged