Feature/epc qr code generator
fond-of-oryx/fond-of-oryx pull request #135
Opened 2021-05-19 05:23 UTC by julianzimmermann

- extracted qr code generator stuff to new package
- use qr code generator package
- refactoring

2021-05-25 06:42 UTC, daniel-rose requested changes

2021-05-25 06:42 UTC, daniel-rose commented on bundles/payment-epc-qr-code/composer.json
> +    "fond-of-oryx/qr-code-generator": "^dev-master",
Use correct version constraint.

2021-05-25 06:42 UTC, daniel-rose commented on bundles/payment-epc-qr-code/src/FondOfOryx/Service/PaymentEpcQrCode/PaymentEpcQrCodeConfig.php
> +        return $this->get(PaymentEpcQrCodeConstants::EPC_QR_CODE_QR_CODE_FORMAT, 'png');
Use const for default value.

2021-05-25 06:42 UTC, daniel-rose commented on bundles/payment-epc-qr-code/src/FondOfOryx/Zed/PaymentEpcQrCode/PaymentEpcQrCodeConfig.php
> +        return $this->get(PaymentEpcQrCodeConstants::EPC_QR_CODE_DATA_VERSION, '002');
Use const for default value.

2021-05-25 06:42 UTC, daniel-rose commented on bundles/payment-epc-qr-code/src/FondOfOryx/Zed/PaymentEpcQrCode/PaymentEpcQrCodeConfig.php
> +        return $this->get(PaymentEpcQrCodeConstants::EPC_QR_CODE_DATA_SERVICE_TAG, 'BCD');
Use const for default value.

2021-05-25 06:42 UTC, daniel-rose commented on bundles/payment-epc-qr-code/src/FondOfOryx/Zed/PaymentEpcQrCode/PaymentEpcQrCodeConfig.php
> +        return $this->get(PaymentEpcQrCodeConstants::EPC_QR_CODE_DATA_ENCODING, 'UTF-8');
Use const for default value.

2021-05-25 06:42 UTC, daniel-rose commented on bundles/payment-epc-qr-code/src/FondOfOryx/Zed/PaymentEpcQrCode/PaymentEpcQrCodeConfig.php
> +        return $this->get(PaymentEpcQrCodeConstants::EPC_QR_CODE_DATA_TYPE, 'SCT');
Use const for default value.

2021-05-25 06:42 UTC, daniel-rose commented on bundles/payment-epc-qr-code/src/FondOfOryx/Zed/PaymentEpcQrCode/PaymentEpcQrCodeConfig.php
> +        return $this->get(PaymentEpcQrCodeConstants::EPC_QR_CODE_DATA_PURPOSE, '');
Use const for default value.

2021-05-25 06:42 UTC, daniel-rose commented on bundles/qr-code-generator/src/FondOfOryx/Service/QrCodeGenerator/Dependency/Wrapper/WriterCollection.php
> +            'png' => static function () use ($self) {
Use const for array keys.

2021-05-25 06:42 UTC, daniel-rose commented on codeception.yml
> +#  - bundles/util-math-formula
Uncomment this lines.

2021-05-25 06:42 UTC, daniel-rose commented on composer.json
> +      "FondOfOryx\\Shared\\QrCodeGenerator\\": "bundles/qr-code-generator/src/FondOfOryx/Shared/QrCodeGenerator",
Use alphabetically sort...

2021-05-25 06:42 UTC, daniel-rose commented on composer.json
> +      "FondOfOryx\\Shared\\QrCodeGenerator\\": "bundles/qr-code-generator/tests/FondOfOryx/Shared/QrCodeGenerator",
Use alphabetically sort...

2021-05-25 06:42 UTC, daniel-rose commented on bundles/payment-epc-qr-code/composer.json
> +    "fond-of-oryx/qr-code-generator": "^dev-master",
Look at dandelion.json

2021-05-25 06:42 UTC, daniel-rose commented on composer.json
> +    "fond-of-oryx/qr-code-generator": "*",
Use alphabetically sort...

2021-05-25 10:26 UTC, sourcecube approved these changes

2021-05-25 10:39 UTC, gengjozsef approved these changes

2021-06-01 11:47 UTC, daniel-rose approved these changes

2021-06-01 11:48 UTC, merged