Feature/availability alert cross engange
fond-of-oryx/fond-of-oryx pull request #15
Opened 2021-03-02 15:52 UTC by julianzimmermann

- extends availability alert basic stuff
- provides plugins for availability alert stuff for XNG

2021-03-02 16:01 UTC, sourcecube commented on composer.json
> +      "FondOfOryx\\Zed\\AvailabilityAlertCrossEngage\\": "bundles/availability-alert-cross-engage/src/FondOfOryx/Zed/AvailabilitAlertCrossEngage",
typo

2021-03-03 06:47 UTC, sourcecube approved these changes

2021-03-03 09:06 UTC, daniel-rose requested changes

2021-03-03 09:06 UTC, daniel-rose commented on bundles/availability-alert-cross-engage/src/FondOfOryx/Yves/AvailabilityAlertCrossEngage/Plugin/CrossEngageAvailabilityAlertSubscriptionRequestExpanderPlugin.php
> +        return $ipAddress;
The request class contains a method with this logic

```php
    /**
     * Returns the client IP addresses.
     *
     * In the returned array the most trusted IP address is first, and the
     * least trusted one last. The "real" client IP address is the last one,
     * but this is also the least trusted one. Trusted proxies are stripped.
     *
     * Use this method carefully; you should use getClientIp() instead.
     *
     * @return array The client IP addresses
     *
     * @see getClientIp()
     */
    public function getClientIps()
    {
        $ip = $this->server->get('REMOTE_ADDR');

        if (!$this->isFromTrustedProxy()) {
            return [$ip];
        }

        return $this->getTrustedValues(self::HEADER_X_FORWARDED_FOR, $ip) ?: [$ip];
    }
```

2021-03-03 09:06 UTC, daniel-rose commented on bundles/availability-alert-cross-engage/src/FondOfOryx/Zed/AvailabilityAlertCrossEngage/Business/Handler/RegisterSubscriberHandler.php
> +        $response->setStatus(true);
Maybe

```php
$response = (new AvailabilityAlertCrossEngageSubscriberRegistrationResponseTransfer())
        ->setSubscriber($subscriberTransfer);
        ->setStatus(true);
```

2021-03-04 08:25 UTC, daniel-rose approved these changes

2021-03-04 08:28 UTC, merged