- move prepayment package from fos too foo
fond-of-oryx/fond-of-oryx pull request #156
Opened 2021-06-01 16:07 UTC by julianzimmermann

2021-06-01 16:11 UTC, daniel-rose requested changes
Please add unit tests...

2021-06-01 16:11 UTC, daniel-rose commented on bundles/prepayment/composer.json
> +    "spryker/symfony": "^3.3.5"
Please check versions...

2021-06-01 16:11 UTC, daniel-rose commented on bundles/prepayment/composer.json
> +    "php": ">=7.2",
EOL for php 7.2. Use >= 7.3.

2021-06-01 16:11 UTC, daniel-rose commented on bundles/prepayment/composer.json
> +    "spryker/symfony": "^3.3.5"
Please check required packages. Kernel is not required for example...

2021-06-07 06:44 UTC, daniel-rose approved these changes

2021-06-07 06:44 UTC, daniel-rose commented on bundles/prepayment/codeception.yml
> +namespace: FondOfOryx
wrong namespace

2021-06-07 06:44 UTC, daniel-rose commented on bundles/prepayment/src/FondOfOryx/Yves/Prepayment/Form/DataProvider/PrepaymentFormDataProvider.php
> +            $dataTransfer->setPayment($paymentTransfer);
Use one line...

2021-06-07 06:44 UTC, daniel-rose commented on bundles/prepayment/src/FondOfOryx/Zed/Prepayment/Communication/Plugin/Checkout/PrepaymentPostCheckPlugin.php
> +                ->setMessage('Something went wrong with your payment. Try again!');
Use one line...

```php
$checkoutErrorTransfer = (new CheckoutErrorTransfer())
    ->setErrorCode(static::ERROR_CODE_PAYMENT_FAILED)
    ->setMessage('Something went wrong with your payment. Try again!');
```

2021-06-07 06:44 UTC, daniel-rose commented on bundles/prepayment/src/FondOfOryx/Zed/Prepayment/PrepaymentConfig.php
> +        return $this->get(PrepaymentConstants::IBAN);
Are you sure, that null is allowed?

2021-06-07 06:45 UTC, gengjozsef approved these changes

2021-06-08 09:12 UTC, merged