bundle: cart-code-type-data-import
fond-of-oryx/fond-of-oryx pull request #229
Opened 2021-07-19 13:00 UTC by DerCalli

**Description**

- new bundle "cart-code-type-data-import"
- unit-tests

2021-07-19 13:10 UTC, daniel-rose requested changes

2021-07-19 13:10 UTC, daniel-rose commented on bundles/cart-code-type-data-import/composer.json
> +    "php": ">=7.3"
Please check your dependencies...

2021-07-19 13:10 UTC, daniel-rose commented on bundles/cart-code-type-data-import/src/FondOfOryx/Zed/CartCodeTypeDataImport/Business/CartCodeTypeDataImportFacadeInterface.php
> +     * - Imports Shipment Table Rate data.
Copy paste failure...

2021-07-19 13:10 UTC, daniel-rose commented on codeception.yml
> -  - bundles/availability-alert-migrator
Why did you remove this line?

2021-07-19 13:24 UTC, DerCalli commented on codeception.yml
> -  - bundles/availability-alert-migrator
oops, just a mistake

2021-07-20 06:15 UTC, sourcecube approved these changes

2021-07-20 08:39 UTC, daniel-rose approved these changes

2021-07-20 08:49 UTC, merged