search for orders with outstanding item quantity
fond-of-oryx/fond-of-oryx pull request #267
Opened 2021-09-01 10:59 UTC by DerCalli

**Changelog**

- New QueryExpanderPlugin to search for orders with outstanding item quantity
- Export `has_outstanding_quantity` attribute to searchable ES properties
- Count outstanding quantity on item-level

![image](https://user-images.githubusercontent.com/35733274/131660065-c10f0e87-ec8f-4c56-82c6-b973e2469356.png)

2021-09-02 09:49 UTC, daniel-rose reviewed
See notes in slack-channel #digital-misc-dev-qa

2021-09-14 12:48 UTC, julianzimmermann requested changes

2021-09-14 12:48 UTC, julianzimmermann commented on bundles/erp-order-page-search/src/FondOfOryx/Zed/ErpOrderPageSearch/Business/Publisher/ErpOrderPageSearchPublisher.php
> +                [static::ERP_ORDER_ITEM_OUTSTANDING_QTY => $item->getOrderedQuantity() - $item->getShippedQuantity()]
There is an interface for presave plugins. Have you evaluated it for adding the outstanding quantity? It could be the better way

2021-09-14 12:49 UTC, daniel-rose requested changes

2021-09-14 12:49 UTC, daniel-rose commented on bundles/erp-order-page-search/src/FondOfOryx/Client/ErpOrderPageSearch/Plugin/SearchExtension/OutstandingQuantityErpPageSearchQueryExpanderPlugin.php
> +        if (!isset($requestParameters[ErpOrderPageSearchConstants::PARAMETER_OUTSTANDING_QUANTITY])) {
I think `PARAMETER_MIN_OUTSTANDING_QUANTITY` could be a better naming. This makes it clearer that is used for a range query.

2021-09-14 12:49 UTC, daniel-rose commented on bundles/erp-order-page-search/src/FondOfOryx/Shared/ErpOrderPageSearch/Schema/erp-order.json
> +          "type": "keyword"
Please use integer as type.

2021-09-14 12:49 UTC, daniel-rose commented on bundles/erp-order-page-search/src/FondOfOryx/Shared/ErpOrderPageSearch/ErpOrderPageSearchConstants.php
> +    public const PARAMETER_OUTSTANDING_QUANTITY = 'outstanding-quantity';
See first comment.

2021-09-14 12:49 UTC, daniel-rose commented on bundles/erp-order-page-search/tests/FondOfOryx/Zed/ErpOrderPageSearch/Business/Mapper/ErpOrderPageSearchDataMapperTest.php
> +            ErpOrderPageSearchDataMapper::OUTSTANDING_QUANTITY => '',
Please use an integer value.

2021-09-14 14:00 UTC, julianzimmermann commented on bundles/erp-order-page-search/src/FondOfOryx/Zed/ErpOrderPageSearch/Business/Publisher/ErpOrderPageSearchPublisher.php
> +                [static::ERP_ORDER_ITEM_OUTSTANDING_QTY => $item->getOrderedQuantity() - $item->getShippedQuantity()]
https://github.com/fond-of-oryx/fond-of-oryx/blob/main/bundles/erp-order/src/FondOfOryx/Zed/ErpOrder/Business/Model/Writer/ErpOrderWriter.php#L128

2021-09-14 14:01 UTC, julianzimmermann commented on bundles/erp-order-page-search/src/FondOfOryx/Zed/ErpOrderPageSearch/Business/Publisher/ErpOrderPageSearchPublisher.php
> +                [static::ERP_ORDER_ITEM_OUTSTANDING_QTY => $item->getOrderedQuantity() - $item->getShippedQuantity()]
With this it should be possible to only create one plugin to extend the data instead of changing the code. Think OCP

2021-09-14 14:04 UTC, julianzimmermann commented on bundles/erp-order-page-search/src/FondOfOryx/Zed/ErpOrderPageSearch/Business/Publisher/ErpOrderPageSearchPublisher.php
> +                [static::ERP_ORDER_ITEM_OUTSTANDING_QTY => $item->getOrderedQuantity() - $item->getShippedQuantity()]
And last but not least... the DB model has no diff to the ES model which reduce confusions for others

2021-09-14 14:11 UTC, daniel-rose commented on bundles/erp-order-page-search/src/FondOfOryx/Zed/ErpOrderPageSearch/Business/Publisher/ErpOrderPageSearchPublisher.php
> +                [static::ERP_ORDER_ITEM_OUTSTANDING_QTY => $item->getOrderedQuantity() - $item->getShippedQuantity()]
Good point @julianzimmermann. I hadn't even thought about it. Let's talk about it again internally.

2021-09-16 06:52 UTC, julianzimmermann approved these changes

2021-09-16 06:52 UTC, julianzimmermann commented on bundles/erp-order/src/FondOfOryx/Zed/ErpOrder/Communication/Plugin/PreSave/ErpOrderCalculateOutstandingQuantityErpOrderPreSavePlugin.php
> +            $item->setOutstandingQuantity($item->getOrderedQuantity() - $item->getShippedQuantity());
could it be possible that getOrderedQuantity or getShippedQuantity is null? In the MW mapper getShippedQuantity could be null
{
        "name": "quantity",
        "type": "int",
        "isNullable": false
      },
      {
        "name": "quantityShipped",
        "type": "int",
        "isNullable": true
      },
      {
        "name": "quantityInvoiced",
        "type": "int",
        "isNullable": true
      },

2021-09-20 12:08 UTC, daniel-rose approved these changes

2021-09-20 12:09 UTC, merged