✨Handle query parameters `is-canceled`, `from` & `to` for `erp-orders-page-search`-request
fond-of-oryx/fond-of-oryx pull request #276
Opened 2023-03-22 15:33 UTC by gengjozsef

- add plugins to expand search query with `is-canceled`, `from` & `to`
- add `isCanceled` property to transfer object
- add constants
- prepare and add unit tests
- ...

2023-03-22 15:39 UTC, sourcecube approved these changes

2023-03-23 07:53 UTC, daniel-rose requested changes

2023-03-23 07:53 UTC, daniel-rose commented on bundles/erp-order-page-search/src/FondOfOryx/Client/ErpOrderPageSearch/Plugin/SearchExtension/ToDateErpOrderPageSearchQueryExpanderPlugin.php
> +                'lte' => $to->format('Y-m-d H:i:s'),
Maybe a constant for the format will be better. You can use this constants also for the class `FromDateErpOrderPageSearchQueryExpanderPlugin`.

2023-03-23 07:53 UTC, daniel-rose commented on bundles/erp-order-page-search/src/FondOfOryx/Client/ErpOrderPageSearch/Plugin/SearchExtension/ToDateErpOrderPageSearchQueryExpanderPlugin.php
> +class ToDateErpOrderPageSearchQueryExpanderPlugin extends AbstractPlugin implements QueryExpanderPluginInterface
I think `ToErpOrderPageSearchQueryExpanderPlugin` will be a better name. It is shorter.

2023-03-23 07:53 UTC, daniel-rose commented on bundles/erp-order-page-search/src/FondOfOryx/Client/ErpOrderPageSearch/Plugin/SearchExtension/FromDateErpOrderPageSearchQueryExpanderPlugin.php
> +class FromDateErpOrderPageSearchQueryExpanderPlugin extends AbstractPlugin implements QueryExpanderPluginInterface
Look at the comments for `ToDateErpOrderPageSearchQueryExpanderPlugin`.

2023-03-23 10:13 UTC, closed without merging