Feature/add generate one time password
fond-of-oryx/fond-of-oryx pull request #41
Opened 2021-03-22 13:07 UTC by SpiderDan98

Add generate one time password

2021-03-22 13:15 UTC, DerCalli approved these changes

2021-03-22 13:55 UTC, daniel-rose requested changes

2021-03-22 13:55 UTC, daniel-rose commented on bundles/one-time-password/src/FondOfOryx/Zed/OneTimePassword/Persistence/OneTimePasswordQueryContainerInterface.php
> +interface OneTimePasswordQueryContainerInterface
Use repository instead of query container...

2021-03-22 13:55 UTC, daniel-rose commented on bundles/one-time-password/src/FondOfOryx/Zed/OneTimePassword/Persistence/OneTimePasswordPersistenceFactory.php
> +        return SpyCustomerQuery::create();
Please inject this query object by dependency provider...

2021-03-22 13:55 UTC, daniel-rose commented on bundles/one-time-password/src/FondOfOryx/Zed/OneTimePassword/Persistence/OneTimePasswordEntityManager.php
> +    public function updateCustomerPassword(SpyCustomerEntityTransfer $customerEntityTransfer): int
Do not use spy objects outside of persistence layer.
Use transfer objects or primitive data types like int, string, ...

```php
public function updateCustomerPassword(CustomerTransfer $customerTransfer): CustomerResponseTransfer
```

2021-03-22 13:55 UTC, daniel-rose commented on bundles/one-time-password/src/FondOfOryx/Zed/OneTimePassword/OneTimePasswordConfig.php
> +    public const GERMAN_WORD_LIST_PATH = '/../../../../Shared/OneTimePassword/data/german-wordlist.txt';
Are you sure, that this path is always correct?

2021-03-22 13:55 UTC, daniel-rose commented on bundles/one-time-password/composer.json
> +    "hackzilla/password-generator": "^1.6"
Are you sure, that this version constraint is correct?

2021-03-22 13:55 UTC, daniel-rose commented on bundles/one-time-password/src/FondOfOryx/Zed/OneTimePassword/Business/Generator/OneTimePasswordGenerator.php
> +        $customerTransfer->fromArray($customerEntity->toArray(), true);
This lines are not business logic. Move it to the correct layer.

2021-03-22 13:55 UTC, daniel-rose commented on bundles/one-time-password/src/FondOfOryx/Zed/OneTimePassword/Business/Generator/OneTimePasswordGenerator.php
> +            ->findOne();
You do not need you own logic for getting customer by email. Have you thought about using getCustomer from the customer facade?. --> https://github.com/spryker/customer/blob/acd13701c1872590b459586f75adb0df83ed36c7/src/Spryker/Zed/Customer/Business/CustomerFacadeInterface.php#L164

2021-03-22 13:55 UTC, daniel-rose commented on bundles/one-time-password/src/FondOfOryx/Zed/OneTimePassword/OneTimePasswordDependencyProvider.php
> +            return $container->getLocator()->customer()->facade();
Please use a bridge...

2021-03-22 13:55 UTC, daniel-rose commented on bundles/one-time-password/src/FondOfOryx/Zed/OneTimePassword/Persistence/OneTimePasswordEntityManagerInterface.php
> +    public function updateCustomerPassword(SpyCustomerEntityTransfer $customerEntityTransfer): int;
Have you thought about using CustomerResponseTransfer as return type.

2021-03-22 14:27 UTC, julianzimmermann reviewed
see comments

2021-03-22 14:27 UTC, julianzimmermann commented on bundles/one-time-password-rest-api/src/FondOfOryx/Zed/OneTimePasswordRestApi/OneTimePasswordRestApiDependencyProvider.php
> +        $container[self::FACADE_ONE_TIME_PASSWORD] = static function (Container $container) {
static

2021-03-22 14:27 UTC, julianzimmermann commented on bundles/one-time-password-rest-api/src/FondOfOryx/Zed/OneTimePasswordRestApi/OneTimePasswordRestApiDependencyProvider.php
> +            return $container->getLocator()->oneTimePassword()->facade();
bridge

2021-03-22 14:27 UTC, julianzimmermann commented on bundles/one-time-password/src/FondOfOryx/Zed/OneTimePassword/Business/Generator/OneTimePasswordGenerator.php
> +            ->findOne();
As DR mentioned or use repo instead

2021-03-22 14:27 UTC, julianzimmermann commented on bundles/one-time-password/src/FondOfOryx/Zed/OneTimePassword/Business/Generator/OneTimePasswordGenerator.php
> +            ->setWordList(__DIR__ . OneTimePasswordConfig::GERMAN_WORD_LIST_PATH)
Maybe use spryker functionality to get the path and whats happen if its an absolut path in config? Make it changeable by config

2021-03-22 14:27 UTC, julianzimmermann commented on bundles/one-time-password/src/FondOfOryx/Zed/OneTimePassword/Business/Generator/OneTimePasswordGenerator.php
> +        return $encoder->encodePassword($currentPassword, self::BCRYPT_SALT);
static

2021-03-22 14:27 UTC, julianzimmermann commented on bundles/one-time-password/src/FondOfOryx/Zed/OneTimePassword/OneTimePasswordConfig.php
> +    public const GERMAN_WORD_LIST_PATH = '/../../../../Shared/OneTimePassword/data/german-wordlist.txt';
make it configurable

2021-03-22 14:27 UTC, julianzimmermann commented on bundles/one-time-password/src/FondOfOryx/Zed/OneTimePassword/OneTimePasswordDependencyProvider.php
> +        $container[self::FACADE_CUSTOMER] = static function (Container $container) {
static

2021-03-22 14:27 UTC, julianzimmermann commented on bundles/one-time-password/src/FondOfOryx/Zed/OneTimePassword/OneTimePasswordDependencyProvider.php
> +            return $container->getLocator()->customer()->facade();
bridge

2021-03-22 14:27 UTC, julianzimmermann commented on bundles/one-time-password/src/FondOfOryx/Zed/OneTimePassword/Persistence/OneTimePasswordPersistenceFactory.php
> +        return SpyCustomerQuery::create();
and use in repo/em

2021-03-22 14:27 UTC, julianzimmermann commented on bundles/one-time-password/src/FondOfOryx/Zed/OneTimePassword/Persistence/OneTimePasswordQueryContainer.php
> +class OneTimePasswordQueryContainer extends AbstractQueryContainer implements OneTimePasswordQueryContainerInterface
Create Repository instead

2021-03-22 14:47 UTC, SpiderDan98 commented on bundles/one-time-password/composer.json
> +    "hackzilla/password-generator": "^1.6"
Yes, because previous versions are only for PHP 5

2021-03-23 07:59 UTC, sourcecube commented
Can we change the title and remove `Feature/` as well as capitalize the title.

2021-03-24 10:27 UTC, daniel-rose approved these changes

2021-03-24 10:29 UTC, merged