Bugfix/fix update erp order
fond-of-oryx/fond-of-oryx pull request #49
Opened 2021-03-24 17:09 UTC by gengjozsef

2021-03-24 17:52 UTC, julianzimmermann approved these changes

2021-03-25 05:30 UTC, daniel-rose requested changes
Sorry, i don't understand this pr.

2021-03-25 05:30 UTC, daniel-rose commented on bundles/erp-order-api/src/FondOfOryx/Shared/ErpOrderApi/Transfer/erp_order_api.transfer.xml
> +    </transfer>
Why?

2021-03-25 05:30 UTC, daniel-rose commented on bundles/erp-order-api/src/FondOfOryx/Zed/ErpOrderApi/Business/ErpOrderApiBusinessFactory.php
> +            $this->createTransferMapper()
Why?

2021-03-25 05:30 UTC, daniel-rose commented on bundles/erp-order-api/src/FondOfOryx/Zed/ErpOrderApi/Business/Mapper/TransferMapper.php
> +    }
Are you sure, that you need this?

2021-03-25 05:30 UTC, daniel-rose commented on bundles/erp-order-api/src/FondOfOryx/Zed/ErpOrderApi/Business/Model/ErpOrderApi.php
> +
What is the reason for that?

2021-03-25 08:11 UTC, gengjozsef commented on bundles/erp-order-api/src/FondOfOryx/Shared/ErpOrderApi/Transfer/erp_order_api.transfer.xml
> +    </transfer>
@daniel-rose because i need it in the find method:

 public function find(ApiRequestTransfer $apiRequestTransfer): ApiCollectionTransfer
    {
        $apiCollectionTransfer = $this->repository->find($apiRequestTransfer);
        $collection = $this->transferMapper->toTransferCollection($apiCollectionTransfer->getData());

method toTransferCollection returns a collection of ErpOrderApiTransfer

2021-03-25 08:12 UTC, gengjozsef commented on bundles/erp-order-api/src/FondOfOryx/Zed/ErpOrderApi/Business/ErpOrderApiBusinessFactory.php
> +            $this->createTransferMapper()
@daniel-rose why i need the transferMapper?

i need it in the same method as above written:

@daniel-rose because i need it in the find method:

 public function find(ApiRequestTransfer $apiRequestTransfer): ApiCollectionTransfer
    {
        $apiCollectionTransfer = $this->repository->find($apiRequestTransfer);
        $collection = $this->transferMapper->toTransferCollection($apiCollectionTransfer->getData());

2021-03-25 08:15 UTC, gengjozsef commented on bundles/erp-order-api/src/FondOfOryx/Zed/ErpOrderApi/Business/Mapper/TransferMapper.php
> +    }
@daniel-rose sure it is hard to answer, probably there is always a better solution. At the moment in my solution, which uses similar implementation process  as we used in other API modules in our projects, and we used a TransferMapper

2021-03-25 08:17 UTC, gengjozsef commented on bundles/erp-order-api/src/FondOfOryx/Zed/ErpOrderApi/Business/Model/ErpOrderApi.php
> +
@daniel-rose i remove the unused variable

2021-03-25 12:52 UTC, daniel-rose approved these changes

2021-03-25 12:54 UTC, merged