Feature: new bundle return label rest api
fond-of-oryx/fond-of-oryx pull request #53
Opened 2021-03-26 13:04 UTC by DerCalli

Implementierung RestApi bis zur Facade. Dort wird später über eine Bridge die Verbindung zu ReturnLaben (weiteres Bundle) hergestellt und das ReturnLabel über die DHL-API geholt.

2021-03-29 06:33 UTC, julianzimmermann approved these changes

2021-03-29 06:33 UTC, julianzimmermann commented on bundles/return-labels-rest-api/src/FondOfOryx/Glue/ReturnLabelsRestApi/Proccesor/Reader/CompanyUnitAddressReader.php
> +
u really need this empty class?

2021-03-29 06:33 UTC, julianzimmermann commented on bundles/return-labels-rest-api/src/FondOfOryx/Glue/ReturnLabelsRestApi/Proccesor/ReturnLabelProcessor.php
> +        $companyUnitAddressTransfer = $this->client->findCompanyUnitAddressByUuid($returnLabelsRestApiTransfer);
where is the permission check?

2021-03-29 16:30 UTC, sourcecube commented on bundles/return-labels-rest-api/.editorconfig
> +indent_size = 2
Can be removed, this should be in monorepo root.

2021-03-29 16:30 UTC, sourcecube commented on bundles/return-labels-rest-api/.gitignore
> +composer.lock
File is not necessary

2021-03-29 16:30 UTC, sourcecube commented on bundles/return-labels-rest-api/LICENSE
> +Copyright (c) 2020 FOND OF GmbH
2021

2021-03-29 16:30 UTC, sourcecube commented on bundles/return-labels-rest-api/composer.json
> +      "Generated\\": "tests/Generated/"
This needs to be `src/Generated`

2021-03-29 16:30 UTC, sourcecube commented on bundles/return-labels-rest-api/composer.json
> +    "fond-of-codeception/spryker": "dev-master",
You can use version 1.0.0 I guess

2021-03-29 16:30 UTC, sourcecube commented on bundles/return-labels-rest-api/src/FondOfOryx/Client/ReturnLabelsRestApi/ReturnLabelsRestApiDependencyProvider.php
> +                $container->getLocator()->companyUserReference()->getClient()
Is `getClient()` the right call here?

2021-03-29 16:30 UTC, sourcecube commented on bundles/return-labels-rest-api/src/FondOfOryx/Client/ReturnLabelsRestApi/Zed/ReturnLabelsRestApiZedStub.php
> +    }
Isn't there a client which exposes this query already? Could this be handled in the Zed Request which creates the label?

2021-03-29 16:30 UTC, sourcecube commented on bundles/return-labels-rest-api/src/FondOfOryx/Shared/ReturnLabelsRestApi/ReturnLabelsConstants.php
> +}
Can be removed if empty

2021-03-29 16:30 UTC, sourcecube commented on dandelion.json
> +        "customer-statistics-rest-api": {
Can you double check that your editor config is working properly and that JSON is indented with 2 spaces.

2021-03-29 16:30 UTC, sourcecube commented on dandelion.json
> +            "version": "1.0.0"
This is old an incorrect, can you check that the branch is uptodate with `main`

2021-03-29 16:32 UTC, sourcecube requested changes
I'm not sure about the plural `s` in the package name and there is a mix in naming in folder and package name

2021-03-29 16:32 UTC, sourcecube commented on codeception.yml
> +  - bundles/return-label-rest-api
Typo ... in general this might be the better name

2021-03-30 10:40 UTC, DerCalli commented on bundles/return-labels-rest-api/src/FondOfOryx/Client/ReturnLabelsRestApi/ReturnLabelsRestApiDependencyProvider.php
> +                $container->getLocator()->companyUserReference()->getClient()
Why not? Or should i implement it in my ZED layer (Facade-Bridge)?

2021-04-07 15:32 UTC, closed without merging