order budget history cleanup
fond-of-oryx/fond-of-oryx pull request #536
Opened 2024-02-27 07:11 UTC by julianzimmermann

- add cleanup command for cleanup of old order budget history entries

2024-02-27 07:30 UTC, daniel-rose requested changes

2024-02-27 07:30 UTC, daniel-rose commented on bundles/order-budget/src/FondOfOryx/Shared/OrderBudget/OrderBudgetConstants.php
> +    public const RETENTION_TIME_IN_DAYS_DEFAULT = 360;
Why 360? 365 = 1 year

2024-02-27 07:30 UTC, daniel-rose commented on bundles/order-budget/src/FondOfOryx/Zed/OrderBudget/Business/Cleanupper/OrderBudgetHistoryCleanupper.php
> +class OrderBudgetHistoryCleanupper implements OrderBudgetHistoryCleanupperInterface
```suggestion
class OrderBudgetHistoryCleaner implements OrderBudgetHistoryCleanerInterface
```

2024-02-27 07:30 UTC, daniel-rose commented on bundles/order-budget/src/FondOfOryx/Zed/OrderBudget/Business/Cleanupper/OrderBudgetHistoryCleanupper.php
> +    public function removeOldHistoryEntries(): void
```suggestion
    public function clean(): void
```

2024-02-27 07:30 UTC, daniel-rose commented on bundles/order-budget/src/FondOfOryx/Zed/OrderBudget/Business/Cleanupper/OrderBudgetHistoryCleanupper.php
> +        $test = new DateTime($maxDate);
```suggestion
        $oldestDate = (new DateTime())->sub(new DateInterval(sprintf('P%sD', $this->config->getHistoryRetentionTime())));
```

2024-02-27 07:30 UTC, daniel-rose commented on bundles/order-budget/src/FondOfOryx/Zed/OrderBudget/Business/OrderBudgetFacade.php
> +    public function removeOldOrderBudgetsFromHistory(): void
```suggestion
    public function cleanupOrderBudgetHistory(): void
```

2024-02-27 07:30 UTC, daniel-rose commented on bundles/order-budget/src/FondOfOryx/Zed/OrderBudget/Communication/Console/OrderBudgetHistoryCleanupConsole.php
> +    public const COMMAND_NAME = 'order-budget:history-cleanup';
```suggestion
    public const COMMAND_NAME = 'order-budget:history:cleanup';
```

2024-02-27 07:30 UTC, daniel-rose commented on bundles/order-budget/src/FondOfOryx/Zed/OrderBudget/Communication/Console/OrderBudgetHistoryCleanupConsole.php
> +    public const DESCRIPTION = 'This command will remove old order budgets.';
```suggestion
    public const DESCRIPTION = 'This command will remove old history entries of order budgets.';
```

2024-02-27 07:30 UTC, daniel-rose commented on bundles/order-budget/src/FondOfOryx/Zed/OrderBudget/Communication/Console/OrderBudgetHistoryCleanupConsole.php
> +        $this->info('Order budgets history cleanup');
```suggestion
        $this->info('Cleanup order budget history');
```

2024-02-27 08:39 UTC, julianzimmermann commented on bundles/order-budget/src/FondOfOryx/Shared/OrderBudget/OrderBudgetConstants.php
> +    public const RETENTION_TIME_IN_DAYS_DEFAULT = 360;
a bank year is 360 days

2024-03-07 15:27 UTC, daniel-rose approved these changes

2024-03-07 15:27 UTC, daniel-rose commented on bundles/order-budget/src/FondOfOryx/Zed/OrderBudget/Business/Cleaner/OrderBudgetHistoryCleaner.php
> +    protected function executeCleanup(): void
```suggestion
    protected function executeClean(): void
```

2024-03-07 15:43 UTC, merged