Feature/erp order page search
fond-of-oryx/fond-of-oryx pull request #9
Opened 2021-02-17 10:20 UTC by julianzimmermann

2021-03-02 16:40 UTC, julianzimmermann reviewed
see comments :)

2021-03-02 16:40 UTC, julianzimmermann commented on bundles/erp-order-page-search-rest-api/src/FondOfOryx/Glue/ErpOrderPageSearchRestApi/Model/Mapper/ErpOrderMapper.php
> +        foreach ($searchResults['erp-orders'] as $erpOrderData) {
move to or use const

2021-03-02 16:40 UTC, julianzimmermann commented on bundles/erp-order-page-search-rest-api/src/FondOfOryx/Glue/ErpOrderPageSearchRestApi/Model/Mapper/ErpOrderMapper.php
> +            $responseTransfer->addErpOrder($this->mapErpOrderItemData($erpOrder, $erpOrderData['erp_order_items']));
move to or use const

2021-03-02 16:40 UTC, julianzimmermann commented on bundles/erp-order-page-search/composer.json
> +    "fond-of-codeception/spryker": "dev-master",
version 1.0.0

2021-03-02 16:40 UTC, julianzimmermann commented on bundles/erp-order-page-search/src/FondOfOryx/Client/ErpOrderPageSearch/Dependency/Client/ErpOrderPageSearchToSessionClientBridge.php
> +<?php
could be removed i think

2021-03-02 16:40 UTC, julianzimmermann commented on bundles/erp-order-page-search/src/FondOfOryx/Client/ErpOrderPageSearch/Dependency/Client/ErpOrderPageSearchToSessionClientInterface.php
> +<?php
could be removed i think

2021-03-02 16:40 UTC, julianzimmermann commented on bundles/erp-order-page-search/src/FondOfOryx/Client/ErpOrderPageSearch/ErpOrderPageSearchDependencyProvider.php
> +        $container[static::CLIENT_SESSION] = static function (Container $container) {
is not used. could be removed when bridge an interface are removed

2021-03-02 16:40 UTC, julianzimmermann commented on bundles/erp-order-page-search/src/FondOfOryx/Client/ErpOrderPageSearch/ErpOrderPageSearchFactory.php
> +        return $this->getProvidedDependency(ErpOrderPageSearchDependencyProvider::CLIENT_SESSION);
could be removed

2021-03-02 16:40 UTC, julianzimmermann commented on bundles/erp-order-page-search/src/FondOfOryx/Zed/ErpOrderPageSearch/Persistence/ErpOrderPageSearchQueryContainer.php
> +class ErpOrderPageSearchQueryContainer extends AbstractQueryContainer implements ErpOrderPageSearchQueryContainerInterface
maybe move to repository

2021-03-02 16:40 UTC, julianzimmermann commented on bundles/erp-order-permission/composer.json
> +    "fond-of-codeception/spryker": "dev-master",
1.0

2021-03-02 16:40 UTC, julianzimmermann commented on bundles/erp-order/composer.json
>      "fond-of-codeception/spryker": "dev-master",
^1.0

2021-03-02 16:40 UTC, julianzimmermann commented on bundles/erp-order/src/FondOfOryx/Zed/ErpOrder/Communication/Console/ErpOrderConsole.php
>          $ref = md5($externalRef);
complete file was for testing purpose only, should be removed later :)

2021-03-03 10:47 UTC, daniel-rose requested changes

2021-03-03 10:47 UTC, daniel-rose commented on bundles/erp-order-page-search-rest-api/composer.json
> +    "php": ">=7.2",
Use php >= 7.3 (7.2 EOL)

2021-03-03 10:47 UTC, daniel-rose commented on bundles/erp-order-page-search-rest-api/composer.json
> +    "fond-of-codeception/spryker": "dev-master",
use fix version

2021-03-03 10:47 UTC, daniel-rose commented on bundles/erp-order-page-search/LICENSE
> +Copyright (c) 2020 FOND OF GmbH
2021 please

2021-03-03 10:47 UTC, daniel-rose commented on bundles/erp-order-page-search/.gitignore
> +composer.lock
ignore src/Generated/ also

2021-03-03 10:47 UTC, daniel-rose commented on bundles/erp-order-page-search/README.md
> +[![PHP from Travis config](https://img.shields.io/travis/php-v/symfony/symfony.svg)](https://php.net/)
Remove travis lines...

2021-03-03 10:47 UTC, daniel-rose commented on bundles/erp-order-page-search/README.md
> +[![license](https://img.shields.io/github/license/mashape/apistatus.svg)](https://packagist.org/packages/fond-of-oryx/erp-order-page-search)
https://img.shields.io/github/license/mashape/apistatus.svg <-- wrong url.

2021-03-03 10:47 UTC, daniel-rose commented on bundles/erp-order-page-search/composer.json
> +    "php": ">=7.2",
Look above. 7.2 EOL

2021-03-03 10:47 UTC, daniel-rose commented on bundles/erp-order-page-search/composer.json
> +      "Generated\\": "tests/Generated/"
that must be
`"Generated\\": "src/Generated/"`

2021-03-03 10:47 UTC, daniel-rose commented on bundles/erp-order-page-search/src/FondOfOryx/Client/ErpOrderPageSearch/Plugin/SearchExtension/AbstractErpOrderPageSearchQueryExpanderPlugin.php
> +        }
Early exit?

2021-03-03 10:47 UTC, daniel-rose commented on bundles/erp-order-page-search/src/FondOfOryx/Client/ErpOrderPageSearch/Plugin/SearchExtension/ErpOrderPageSearchCompanyBusinessUnitUuidFilterQueryExpanderPlugin.php
> +            unset($this->currentUser);
Early exit?

2021-03-03 10:47 UTC, daniel-rose commented on bundles/erp-order-page-search/src/FondOfOryx/Client/ErpOrderPageSearch/Plugin/SearchExtension/ErpOrderPageSearchOwnParamFilterQueryExpanderPlugin.php
> +            unset($this->currentUser);
Early exit?

2021-03-03 10:47 UTC, daniel-rose commented on bundles/erp-order-permission/LICENSE
> +Copyright (c) 2020 FOND OF GmbH
2021

2021-03-03 10:47 UTC, daniel-rose commented on bundles/erp-order-permission/README.md
> +[![PHP from Travis config](https://img.shields.io/travis/php-v/symfony/symfony.svg)](https://php.net/)
Remove travis stuff...

2021-03-03 10:47 UTC, daniel-rose commented on bundles/erp-order-permission/README.md
> +[![license](https://img.shields.io/github/license/mashape/apistatus.svg)](https://packagist.org/packages/fond-of-oryx/erp-order-permission)
https://img.shields.io/github/license/mashape/apistatus.svg --> wrong url

2021-03-03 10:47 UTC, daniel-rose commented on bundles/erp-order-permission/composer.json
> +    "php": ">=7.2"
EOL. Please use >= 7.3

2021-03-03 10:47 UTC, daniel-rose commented on bundles/erp-order-permission/composer.json
> +      "Generated\\": "tests/Generated/"
`"Generated\\": "src/Generated/"`

2021-03-03 10:47 UTC, daniel-rose commented on bundles/erp-order/composer.json
>      "php": ">=7.2",
EOL. Please use >=7.3

2021-03-03 10:47 UTC, daniel-rose commented on composer.json
>      "php": ">=7.2",
EOL. Please use >=7.3

2021-03-03 11:07 UTC, sourcecube approved these changes

2021-03-03 11:07 UTC, sourcecube commented on dandelion.json
>              "version": "alpha-0.0.1"
incorrect version.. should be something like `1.0.0-alpha.0`

2021-03-04 09:01 UTC, gengjozsef commented on bundles/erp-order-page-search-rest-api/LICENSE
> +Copyright (c) 2020 FOND OF GmbH
@daniel-rose fixed

2021-03-04 09:04 UTC, gengjozsef commented on bundles/erp-order-page-search-rest-api/composer.json
> +    "php": ">=7.2",
@daniel-rose fixed

2021-03-04 09:11 UTC, gengjozsef commented on bundles/erp-order-page-search-rest-api/composer.json
> +    "fond-of-codeception/spryker": "dev-master",
@daniel-rose fixed

2021-03-04 09:12 UTC, gengjozsef commented on bundles/erp-order-page-search-rest-api/src/FondOfOryx/Glue/ErpOrderPageSearchRestApi/Model/Mapper/ErpOrderMapper.php
> +        foreach ($searchResults['erp-orders'] as $erpOrderData) {
@daniel-rose i build in the constants

2021-03-04 10:36 UTC, daniel-rose approved these changes

2021-03-04 10:36 UTC, daniel-rose commented on bundles/erp-order-page-search-rest-api/src/FondOfOryx/Glue/ErpOrderPageSearchRestApi/Model/Mapper/ErpOrderMapper.php
> +            $erpOrder->fromArray($erpOrderData, true);
Maybe
```php
$erpOrder = (new ErpOrderTransfer())
    ->fromArray($erpOrderData, true);
```

2021-03-04 10:36 UTC, daniel-rose commented on bundles/erp-order-page-search-rest-api/src/FondOfOryx/Glue/ErpOrderPageSearchRestApi/Model/Mapper/ErpOrderMapper.php
> +            $erpOrder->fromArray($erpOrderData, true);
Maybe erpOrderTransfer will be a better name

2021-03-04 11:29 UTC, merged